USE [BootSharp]
GO

--DROPPING EXISTING
IF OBJECT_ID('BootSharp.dbo.B', 'U') IS NOT NULL
  DROP TABLE dbo.[B];
GO

IF OBJECT_ID('BootSharp.dbo.AC', 'U') IS NOT NULL
  DROP TABLE [BootSharp].dbo.[AC]; 
GO

IF OBJECT_ID('BootSharp.dbo.C', 'U') IS NOT NULL
  DROP TABLE [BootSharp].dbo.[C]; 
GO

IF OBJECT_ID('BootSharp.dbo.A', 'U') IS NOT NULL
  DROP TABLE [BootSharp].dbo.[A]; 
GO

--CREATING TABLES
CREATE TABLE A
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(512) DEFAULT 'NOT SET'
)
GO

CREATE TABLE B
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(512) DEFAULT 'NOT SET',
	A_Id BIGINT NOT NULL,
	FOREIGN KEY (A_Id) REFERENCES A(Id)
)
GO

CREATE TABLE C
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(512) DEFAULT 'NOT SET'
)
GO

CREATE TABLE AC
(
	A_Id BIGINT NOT NULL,
	C_Id BIGINT NOT NULL,
	FOREIGN KEY (A_Id) REFERENCES A(Id),
	FOREIGN KEY (C_Id) REFERENCES C(Id)
)
GO



